import {defaultRounds,validateRounds} from './rounds.js?v=8';
import {ArtStore,prepareImage} from './admin-storage.js?v=8';
export const artStore=new ArtStore();
export function setupAdmin({onOpen,onSave}){
 const $=s=>document.querySelector(s),dialog=$('#admin-dialog');let stage=1,draft={},previewUrls=[],selection=0,session=0,pending=0,rounds=defaultRounds();
 function roundFields(){const round=rounds[stage-1];for(const key of ['target','timeLimit','enemyCount','enemySpeed'])$('#round-'+key).value=round[key];}
 function roundOptions(){const select=$('#admin-stage');select.replaceChildren(...rounds.map((_,i)=>{const option=document.createElement('option');option.value=i+1;option.textContent=(i+1)+'라운드';return option;}));select.value=stage;}
 function readFields(){rounds[stage-1]=Object.fromEntries(['target','timeLimit','enemyCount','enemySpeed'].map(key=>[key,Number($('#round-'+key).value)]));return validateRounds(rounds);}
 const status=s=>{$('#admin-status').textContent=s;};
 function cleanUrls(){previewUrls.forEach(u=>URL.revokeObjectURL(u));previewUrls=[];}
 function preview(){cleanUrls();for(const key of ['base','bonus']){const url=draft[key]?URL.createObjectURL(draft[key]):key==='base'?'pool.jpg':'bonus.jpg';if(draft[key])previewUrls.push(url);$('#preview-'+key).src=url;$('#label-'+key).textContent=draft[key]?'내 그림':'기본 그림';}}
 async function loadStage(){const token=++selection;const selected=Number($('#admin-stage').value);$('#save-art').disabled=true;try{const images=await artStore.stage(selected);if(token!==selection)return;stage=selected;draft=images;roundFields();$('#upload-base').value='';$('#upload-bonus').value='';preview();status('그림을 선택하고 저장을 눌러줘.');}catch(e){status(e.message);}finally{if(token===selection)$('#save-art').disabled=false;}}
 $('#admin-open').addEventListener('click',async()=>{++session;onOpen();artStore.lock();$('#admin-submit').disabled=true;$('#admin-editor').hidden=true;$('#admin-auth').hidden=false;$('#admin-password').value='';status('');$('#admin-stage').disabled=false;$('#restore-art').disabled=false;$('#round-add').disabled=false;$('#round-remove').disabled=false;dialog.showModal();$('#admin-submit').disabled=false;$('#storage-mode').textContent=artStore.remote?'서버 저장: 다른 기기와 그림·라운드를 공유해.':'현재 기기 저장 · 서버 연결 전이라 다른 기기에는 적용되지 않아.';$('#admin-password').focus();});
 $('#admin-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{session++;artStore.lock();selection++;pending=0;cleanUrls();$('#admin-password').value='';});
 $('#admin-auth').addEventListener('submit',async e=>{e.preventDefault();const current=session;const password=$('#admin-password').value;$('#admin-submit').disabled=true;try{await artStore.login(password);if(current!==session||!dialog.open){artStore.lock();return;}$('#admin-password').value='';$('#admin-auth').hidden=true;$('#admin-editor').hidden=false;rounds=await artStore.rounds();stage=Math.min(stage,rounds.length);roundOptions();await loadStage();}catch(error){status(error.message);}finally{$('#admin-submit').disabled=false;}});
 $('#admin-stage').addEventListener('change',async()=>{try{readFields();await loadStage();}catch(e){$('#admin-stage').value=stage;status(e.message);}});
 $('#round-add').addEventListener('click',async()=>{if(rounds.length>=20)return status('최대 20라운드야.');try{readFields();rounds.push({...rounds.at(-1)});stage=rounds.length;roundOptions();await loadStage();status('라운드 추가됨 · 저장을 눌러야 적용돼.');}catch(e){status(e.message);}});
 $('#round-remove').addEventListener('click',async()=>{if(rounds.length<=1)return status('라운드가 하나는 있어야 해.');rounds.pop();stage=Math.min(stage,rounds.length);roundOptions();await loadStage();status('마지막 라운드 제외됨 · 저장을 눌러야 적용돼.');});
 for(const key of ['base','bonus'])$('#upload-'+key).addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;const token=selection;pending++;$('#save-art').disabled=true;$('#admin-stage').disabled=true;$('#restore-art').disabled=true;$('#round-add').disabled=true;$('#round-remove').disabled=true;status('그림 준비 중…');try{const blob=await prepareImage(file);if(token!==selection||!artStore.unlocked)return;draft={...draft,[key]:blob};preview();status('미리보기 확인 후 저장을 눌러줘.');}catch(error){status(error.message);}finally{if(token===selection){pending--;$('#save-art').disabled=pending>0;$('#admin-stage').disabled=pending>0;$('#restore-art').disabled=pending>0;$('#round-add').disabled=pending>0;$('#round-remove').disabled=pending>0;}}});
 $('#save-art').addEventListener('click',async()=>{$('#save-art').disabled=true;try{readFields();await artStore.save(stage,draft,rounds);if(!artStore.remote)await artStore.saveRounds(rounds);await onSave(stage);status(stage+'라운드 '+(artStore.remote?'서버 저장':'이 기기 저장')+' 완료 · 설정은 새 게임부터 적용돼.');}catch(e){status('저장 실패: '+e.message);}finally{$('#save-art').disabled=false;}});
 $('#restore-art').addEventListener('click',async()=>{try{await artStore.restore(stage);await loadStage();await onSave(stage);status(stage+'스테이지를 기본 그림으로 바꿨어.');}catch(e){status(e.message);}});
}
