import {ArtStore,prepareImage} from './admin-storage.js?v=6';
export const artStore=new ArtStore();
export function setupAdmin({onOpen,onSave}){
 const $=s=>document.querySelector(s),dialog=$('#admin-dialog');let stage=1,draft={},previewUrls=[],selection=0,session=0,pending=0;
 const status=s=>{$('#admin-status').textContent=s;};
 function cleanUrls(){previewUrls.forEach(u=>URL.revokeObjectURL(u));previewUrls=[];}
 function preview(){cleanUrls();for(const key of ['base','bonus']){const url=draft[key]?URL.createObjectURL(draft[key]):key==='base'?'pool.jpg':'bonus.jpg';if(draft[key])previewUrls.push(url);$('#preview-'+key).src=url;$('#label-'+key).textContent=draft[key]?'내 그림':'기본 그림';}}
 async function loadStage(){const token=++selection;const selected=Number($('#admin-stage').value);$('#save-art').disabled=true;try{const images=await artStore.stage(selected);if(token!==selection)return;stage=selected;draft=images;$('#upload-base').value='';$('#upload-bonus').value='';preview();status('그림을 선택하고 저장을 눌러줘.');}catch(e){status(e.message);}finally{if(token===selection)$('#save-art').disabled=false;}}
 $('#admin-open').addEventListener('click',async()=>{++session;onOpen();artStore.lock();$('#admin-submit').disabled=true;$('#admin-editor').hidden=true;$('#admin-auth').hidden=false;$('#admin-password').value='';status('');$('#admin-stage').disabled=false;$('#restore-art').disabled=false;dialog.showModal();$('#admin-submit').disabled=false;$('#admin-password').focus();});
 $('#admin-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{session++;artStore.lock();selection++;pending=0;cleanUrls();$('#admin-password').value='';});
 $('#admin-auth').addEventListener('submit',async e=>{e.preventDefault();const current=session;const password=$('#admin-password').value;$('#admin-submit').disabled=true;try{await artStore.login(password);if(current!==session||!dialog.open){artStore.lock();return;}$('#admin-password').value='';$('#admin-auth').hidden=true;$('#admin-editor').hidden=false;await loadStage();}catch(error){status(error.message);}finally{$('#admin-submit').disabled=false;}});
 $('#admin-stage').addEventListener('change',loadStage);
 for(const key of ['base','bonus'])$('#upload-'+key).addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;const token=selection;pending++;$('#save-art').disabled=true;$('#admin-stage').disabled=true;$('#restore-art').disabled=true;status('그림 준비 중…');try{const blob=await prepareImage(file);if(token!==selection||!artStore.unlocked)return;draft={...draft,[key]:blob};preview();status('미리보기 확인 후 저장을 눌러줘.');}catch(error){status(error.message);}finally{if(token===selection){pending--;$('#save-art').disabled=pending>0;$('#admin-stage').disabled=pending>0;$('#restore-art').disabled=pending>0;}}});
 $('#save-art').addEventListener('click',async()=>{$('#save-art').disabled=true;try{await artStore.save(stage,draft);await onSave(stage);status(stage+'스테이지 그림 저장 완료!');}catch(e){status('저장 실패: '+e.message);}finally{$('#save-art').disabled=false;}});
 $('#restore-art').addEventListener('click',async()=>{try{await artStore.restore(stage);await loadStage();await onSave(stage);status(stage+'스테이지를 기본 그림으로 바꿨어.');}catch(e){status(e.message);}});
}
