import {Game,W,H,EMPTY,SAFE,TRAIL} from './engine.js';
const $=s=>document.querySelector(s),game=new Game(),canvas=$('#canvas'),ctx=canvas.getContext('2d'),art=new Image();art.src='pool.jpg';let loaded=false,renderPlayer={x:1,y:45},last=0,flash=0,sound=false,audio=null,activePointer=null,origin={x:0,y:0},direction=null;
art.onload=()=>{loaded=true;};art.onerror=()=>{$('#overlay-copy').textContent='그림을 불러오지 못했어. 새로고침해서 다시 해보자.';$('#primary').disabled=true;};
function stop(){direction=null;activePointer=null;game.stop();$('#pad').classList.remove('active');}
function beep(type){if(!sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const osc=audio.createOscillator(),gain=audio.createGain();osc.connect(gain);gain.connect(audio.destination);const now=audio.currentTime;osc.type='sine';osc.frequency.setValueAtTime(type==='hit'?130:660,now);osc.frequency.exponentialRampToValueAtTime(type==='hit'?60:990,now+.13);gain.gain.setValueAtTime(.08,now);gain.gain.exponentialRampToValueAtTime(.001,now+.18);osc.start(now);osc.stop(now+.2);}catch{}}
function message(s){$('#message').textContent=s;}
function overlay(){const s=game.status,visible=s!=='playing';$('#overlay').hidden=!visible;$('#overlay').classList.toggle('clear',s==='clear'||s==='complete');$('#pause').textContent=s==='paused'?'▶':'Ⅱ';$('#pause').setAttribute('aria-label',s==='paused'?'계속하기':'일시정지');$('#secondary').hidden=!(s==='paused'||s==='clear');
 if(s==='ready')return;
 if(s==='paused'){$('#eyebrow').textContent='PAUSED';$('#overlay-title').textContent='잠깐 쉬어가기';$('#overlay-copy').textContent='다시 시작하면 멈춘 곳에서 이어가.';$('#primary').textContent='계속하기';}
 if(s==='clear'){$('#eyebrow').textContent='STAGE CLEAR';$('#overlay-title').textContent='그림 해금!';$('#overlay-copy').textContent=`${game.area().toFixed(1)}% 점령 · ${game.score.toLocaleString()}점`;$('#primary').textContent=game.stage===5?'최종 결과':'다음 스테이지';}
 if(s==='gameover'||s==='complete'){$('#eyebrow').textContent=s==='complete'?'ALL CLEAR':'GAME OVER';$('#overlay-title').textContent=s==='complete'?'다 먹었다 ㅋㅋ':'한 판 더?';$('#overlay-copy').textContent=`${game.stage}스테이지 · ${game.score.toLocaleString()}점`;$('#primary').textContent='다시 도전';}
}
function hud(){const area=game.area();$('#lives').textContent='♥ '.repeat(game.lives)+'♡ '.repeat(3-game.lives);$('#lives').setAttribute('aria-label',`목숨 ${game.lives}개`);$('#score').textContent=String(game.score).padStart(6,'0').replace(/\B(?=(\d{3})+(?!\d))/g,',');$('#stage').textContent=`STAGE ${String(game.stage).padStart(2,'0')}`;$('#area').textContent=`점령 ${area.toFixed(1)}%`;$('#goal').textContent=`목표 ${game.target}%`;const progress=Math.min(100,area/game.target*100);$('#fill').style.width=progress+'%';$('.track').setAttribute('aria-valuenow',String(Math.round(progress)));}
function draw(dt){const sx=canvas.width/W,sy=canvas.height/H;ctx.clearRect(0,0,canvas.width,canvas.height);if(loaded)ctx.drawImage(art,0,0,canvas.width,canvas.height);else{ctx.fillStyle='#13233b';ctx.fillRect(0,0,canvas.width,canvas.height);}const clear=game.status==='clear'||game.status==='complete';if(clear)return;ctx.fillStyle='rgba(12,23,43,.98)';for(let y=0;y<H;y++){let run=-1;for(let x=0;x<=W;x++){const dark=x<W&&game.grid[y*W+x]!==SAFE;if(dark&&run<0)run=x;if(!dark&&run>=0){ctx.fillRect(run*sx,y*sy,(x-run)*sx,sy+.1);run=-1;}}}
 ctx.strokeStyle='rgba(112,144,186,.07)';ctx.lineWidth=1;ctx.beginPath();for(let x=0;x<W;x+=3){ctx.moveTo(x*sx,0);ctx.lineTo(x*sx,H*sy);}for(let y=0;y<H;y+=3){ctx.moveTo(0,y*sy);ctx.lineTo(W*sx,y*sy);}ctx.stroke();ctx.strokeStyle='#78e6ee';ctx.lineWidth=1.4;ctx.beginPath();for(let y=0;y<H;y++)for(let x=0;x<W;x++)if(game.grid[y*W+x]===SAFE){if(game.cell(x+1,y)!==SAFE){ctx.moveTo((x+1)*sx,y*sy);ctx.lineTo((x+1)*sx,(y+1)*sy);}if(game.cell(x-1,y)!==SAFE){ctx.moveTo(x*sx,y*sy);ctx.lineTo(x*sx,(y+1)*sy);}if(game.cell(x,y+1)!==SAFE){ctx.moveTo(x*sx,(y+1)*sy);ctx.lineTo((x+1)*sx,(y+1)*sy);}if(game.cell(x,y-1)!==SAFE){ctx.moveTo(x*sx,y*sy);ctx.lineTo((x+1)*sx,y*sy);}}ctx.stroke();
 if(game.trail.length){ctx.strokeStyle='#ffdc97';ctx.lineWidth=3.5;ctx.lineJoin='round';ctx.shadowColor='#ffc976';ctx.shadowBlur=9;ctx.beginPath();ctx.moveTo((game.lastSafe.x+.5)*sx,(game.lastSafe.y+.5)*sy);for(const p of game.trail)ctx.lineTo((p.x+.5)*sx,(p.y+.5)*sy);ctx.stroke();ctx.shadowBlur=0;}
 for(const e of game.enemies){ctx.shadowColor='#ff507c';ctx.shadowBlur=18;ctx.fillStyle='#ff507c';ctx.beginPath();ctx.arc(e.x*sx,e.y*sy,6,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#ffc1d0';ctx.beginPath();ctx.arc(e.x*sx-1.5,e.y*sy-2,1.5,0,Math.PI*2);ctx.fill();}
 const lerp=1-Math.exp(-dt*40);renderPlayer.x+=(game.player.x-renderPlayer.x)*lerp;renderPlayer.y+=(game.player.y-renderPlayer.y)*lerp;if(!game.cooldown||Math.floor(game.cooldown*12)%2){ctx.fillStyle='#fff1d0';ctx.shadowColor='#ffdc97';ctx.shadowBlur=12;ctx.beginPath();ctx.arc((renderPlayer.x+.5)*sx,(renderPlayer.y+.5)*sy,5.5,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;}if(flash>0){ctx.fillStyle=`rgba(120,230,238,${flash*.25})`;ctx.fillRect(0,0,canvas.width,canvas.height);flash=Math.max(0,flash-dt*3);}}
function frame(t){const dt=last?Math.min((t-last)/1000,.05):0;last=t;const old=game.status;game.update(dt);for(const e of game.events.splice(0)){if(e.type==='hit'){stop();renderPlayer={...game.player};message(game.lives?'선이 끊겼어! 안전한 땅에서 다시 출발':'목숨을 다 썼어');beep('hit');$('#board').classList.remove('hit');void $('#board').offsetWidth;$('#board').classList.add('hit');navigator.vibrate?.(50);}if(e.type==='capture'){flash=1;message(`+${e.points.toLocaleString()}점 · ${e.gained.toFixed(1)}% 획득${e.combo>1?' · 콤보 ×'+e.combo:''}`);beep('capture');}if(e.type==='clear'){stop();message('그림 전체 해금!');}}if(game.status!==old)overlay();hud();draw(dt);requestAnimationFrame(frame);}
function start(){stop();game.start();renderPlayer={...game.player};message('손 떼면 정지 · 선 긋기는 자동');overlay();hud();}
$('#primary').addEventListener('click',()=>{if(game.status==='paused'){game.pause();overlay();}else if(game.status==='clear'){game.next();renderPlayer={...game.player};overlay();message('새 스테이지 · 적을 피해 영역을 연결하자');}else start();});$('#secondary').addEventListener('click',start);$('#pause').addEventListener('click',()=>{stop();game.pause();overlay();});
$('#speed').addEventListener('change',e=>{game.speed=Number(e.target.value);message('이동 속도: '+e.target.selectedOptions[0].textContent);});$('#sound').addEventListener('click',()=>{sound=!sound;$('#sound').textContent=sound?'소리 켜짐':'소리 꺼짐';$('#sound').setAttribute('aria-pressed',String(sound));if(sound)beep('capture');});
const pad=$('#pad');function setDirection(d){if(direction!==d){direction=d;game.direction(d);}}
pad.addEventListener('pointerdown',e=>{if(activePointer!==null||game.status!=='playing'||game.cooldown)return;e.preventDefault();activePointer=e.pointerId;pad.setPointerCapture(activePointer);origin={x:e.clientX,y:e.clientY};const r=pad.getBoundingClientRect();for(const el of [$('#base'),$('#knob')]){el.style.left=(e.clientX-r.left)+'px';el.style.top=(e.clientY-r.top)+'px';}pad.classList.add('active');});
pad.addEventListener('pointermove',e=>{if(e.pointerId!==activePointer)return;e.preventDefault();const dx=e.clientX-origin.x,dy=e.clientY-origin.y,len=Math.hypot(dx,dy),r=pad.getBoundingClientRect(),scale=len>26?26/len:1;$('#knob').style.left=(origin.x-r.left+dx*scale)+'px';$('#knob').style.top=(origin.y-r.top+dy*scale)+'px';if(len<10){setDirection(null);return;}const h=Math.abs(dx),v=Math.abs(dy);if((direction==='left'||direction==='right')&&v<h*1.2)setDirection(dx>=0?'right':'left');else if((direction==='up'||direction==='down')&&h<v*1.2)setDirection(dy>=0?'down':'up');else setDirection(h>v?(dx>=0?'right':'left'):(dy>=0?'down':'up'));});
for(const event of ['pointerup','pointercancel','lostpointercapture'])pad.addEventListener(event,e=>{if(e.pointerId===activePointer)stop();});
const keys={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right'};const held=[];window.addEventListener('keydown',e=>{if(e.target.tagName==='SELECT')return;if(keys[e.key]){e.preventDefault();if(!held.includes(e.key))held.push(e.key);setDirection(keys[e.key]);}else if(e.code==='Space'){e.preventDefault();stop();game.pause();overlay();}});window.addEventListener('keyup',e=>{if(keys[e.key]){e.preventDefault();const i=held.indexOf(e.key);if(i>=0)held.splice(i,1);setDirection(held.length?keys[held[held.length-1]]:null);}});
function backgroundPause(){held.length=0;stop();if(game.status==='playing'){game.pause();overlay();}}window.addEventListener('blur',backgroundPause);document.addEventListener('visibilitychange',()=>{if(document.hidden)backgroundPause();});
const mc=document.modelContext;if(mc?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});for(const tool of [{name:'get_game_status',title:'게임 상태 확인',description:'현재 스테이지, 목숨, 점수, 점령률을 확인합니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(input&&Object.keys(input).length)throw new Error('No input properties allowed');return game.snapshot();}},{name:'restart_game',title:'게임 다시 시작',description:'현재 진행을 버리고 첫 스테이지를 새로 시작합니다.',inputSchema:{type:'object',properties:{confirm:{type:'boolean',const:true}},required:['confirm'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||input.confirm!==true||Object.keys(input).some(k=>k!=='confirm'))throw new Error('confirm:true is required');start();return game.snapshot();}}]){try{Promise.resolve(mc.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}}
overlay();hud();requestAnimationFrame(frame);
