import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,W,H,EMPTY,SAFE,TRAIL} from '../engine.js';
function split(x,enemies){const g=new Game();g.start();g.player={x,y:1};g.lastSafe={...g.player};g.enemies=enemies;g.direction('down');for(let i=0;i<87;i++)g.step();return g;}
test('closed cut captures enemy-free side and leaves enemy side intact',()=>{const g=split(30,[{x:45,y:45,vx:1,vy:1}]);assert.equal(g.cell(10,45),SAFE);assert.equal(g.cell(45,45),EMPTY);assert.equal(g.cell(30,45),SAFE);assert.equal(g.trail.length,0);assert.ok(g.score>0);});
test('enemies on both sides preserve both regions',()=>{const g=split(30,[{x:15,y:45,vx:1,vy:1},{x:45,y:45,vx:1,vy:1}]);assert.equal(g.cell(15,45),EMPTY);assert.equal(g.cell(45,45),EMPTY);assert.equal(g.cell(30,45),SAFE);assert.ok(g.area()<15);});
test('large capture clears stage and next stage retains score',()=>{const g=split(50,[{x:56,y:45,vx:1,vy:1}]);assert.equal(g.status,'clear');assert.ok(g.area()>=75);const score=g.score;g.next();assert.equal(g.stage,2);assert.equal(g.enemies.length,2);assert.equal(g.status,'playing');assert.equal(g.score,score);});
test('backtracking retracts trail and crossing it loses one life',()=>{const g=new Game();g.start();g.direction('right');g.step();g.step();g.step();assert.equal(g.trail.length,3);g.direction('left');g.step();assert.equal(g.trail.length,2);assert.equal(g.cell(4,45),EMPTY);g.direction('down');g.step();g.direction('left');g.step();g.direction('up');g.step();assert.equal(g.lives,2);assert.equal(g.trail.length,0);assert.equal(g.cell(2,45),EMPTY);});
test('enemy touching a trail removes it and preserves captured land',()=>{const g=new Game();g.start();g.direction('right');g.step();const area=g.area();g.enemies=[{x:2.5,y:45.5,vx:0,vy:0}];g.update(.016);assert.equal(g.lives,2);assert.equal(g.cell(2,45),EMPTY);assert.equal(g.area(),area);assert.deepEqual(g.player,g.lastSafe);g.hit();assert.equal(g.lives,2);});
test('pause and stop prevent player movement',()=>{const g=new Game();g.start();g.direction('down');g.pause();const p={...g.player};g.update(1);assert.deepEqual(g.player,p);assert.equal(g.elapsed,0);g.pause();g.direction('down');g.stop();g.update(.05);assert.deepEqual(g.player,p);});
test('enemy remains inside unclaimed region after repeated wall bounces',()=>{const g=new Game();g.start();for(let i=0;i<5000;i++)g.update(.016);const e=g.enemies[0];assert.ok(e.x>2&&e.x<W-2&&e.y>2&&e.y<H-2);assert.equal(g.cell(Math.floor(e.x),Math.floor(e.y)),EMPTY);});
