import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,W,H,EMPTY,SAFE,TRAIL} from '../engine.js';
function split(x,enemies){const g=new Game();g.start();g.player={x,y:1};g.lastSafe={...g.player};g.enemies=enemies;g.direction('down');for(let i=0;i<87;i++)g.step();return g;}
test('closed cut captures enemy-free side and leaves enemy side intact',()=>{const g=split(30,[{x:45,y:45,vx:1,vy:1}]);assert.equal(g.cell(10,45),SAFE);assert.equal(g.cell(45,45),EMPTY);assert.equal(g.cell(30,45),SAFE);assert.equal(g.trail.length,0);assert.ok(g.score>0);});
test('enemies on both sides fill the smaller region and relocate its enemy',()=>{const g=split(20,[{x:10.5,y:45.5,vx:1,vy:1},{x:45.5,y:45.5,vx:1,vy:1}]);assert.equal(g.cell(10,45),SAFE);assert.equal(g.cell(45,45),EMPTY);assert.equal(g.cell(20,45),SAFE);assert.ok(g.area()>35);for(const e of g.enemies){assert.equal(g.cell(Math.floor(e.x),Math.floor(e.y)),EMPTY);assert.equal(g.blocked(e.x,e.y),false);}for(let i=0;i<200;i++)g.update(.016);for(const e of g.enemies)assert.equal(g.cell(Math.floor(e.x),Math.floor(e.y)),EMPTY);});
test('90 percent capture clears stage and next stage retains score',()=>{const g=split(53,[{x:57.5,y:45,vx:1,vy:1}]);assert.equal(g.status,'clear');assert.ok(g.area()>=90);const score=g.score;g.next();assert.equal(g.stage,2);assert.equal(g.enemies.length,2);assert.equal(g.status,'playing');assert.equal(g.score,score);assert.equal(g.bonusUnlocked,false);});
test('backtracking retracts trail and crossing it loses one life',()=>{const g=new Game();g.start();g.direction('right');g.step();g.step();g.step();assert.equal(g.trail.length,3);g.direction('left');g.step();assert.equal(g.trail.length,2);assert.equal(g.cell(4,45),EMPTY);g.direction('down');g.step();g.direction('left');g.step();g.direction('up');g.step();assert.equal(g.lives,2);assert.equal(g.trail.length,0);assert.equal(g.cell(2,45),EMPTY);});
test('enemy touching a trail removes it and preserves captured land',()=>{const g=new Game();g.start();g.direction('right');g.step();const area=g.area();g.enemies=[{x:2.5,y:45.5,vx:0,vy:0}];g.update(.016);assert.equal(g.lives,2);assert.equal(g.cell(2,45),EMPTY);assert.equal(g.area(),area);assert.deepEqual(g.player,g.lastSafe);g.hit();assert.equal(g.lives,2);});
test('pause and stop prevent player movement',()=>{const g=new Game();g.start();g.direction('down');g.pause();const p={...g.player};g.update(1);assert.deepEqual(g.player,p);assert.equal(g.elapsed,0);g.pause();g.direction('down');g.stop();g.update(.05);assert.deepEqual(g.player,p);});
test('enemy remains inside unclaimed region after repeated wall bounces',()=>{const g=new Game();g.start();for(let i=0;i<5000;i++)g.update(.016);const e=g.enemies[0];assert.ok(e.x>2&&e.x<W-2&&e.y>2&&e.y<H-2);assert.equal(g.cell(Math.floor(e.x),Math.floor(e.y)),EMPTY);});
test('release retraces a bent trail to its origin without gaining land or points',()=>{const g=new Game();g.start();g.enemies=[];const origin={...g.player},area=g.area();g.direction('right');for(let i=0;i<8;i++)g.step();g.direction('up');for(let i=0;i<5;i++)g.step();const route=g.trail.map(p=>({...p}));g.release();assert.equal(g.returning,true);g.returnStep();assert.deepEqual(g.player,route[route.length-2]);assert.equal(g.cell(route.at(-1).x,route.at(-1).y),EMPTY);for(let i=0;i<50;i++)g.update(.05);assert.deepEqual(g.player,origin);assert.equal(g.trail.length,0);assert.equal(g.returning,false);assert.equal(g.area(),area);assert.equal(g.score,0);});
test('enemy can still cut the remaining line during automatic return',()=>{const g=new Game();g.start();g.direction('right');for(let i=0;i<8;i++)g.step();g.release();g.enemies=[{x:3.5,y:45.5,vx:0,vy:0}];g.update(.01);assert.equal(g.lives,2);assert.equal(g.returning,false);assert.equal(g.trail.length,0);});
test('new direction interrupts return and preserves turning progress',()=>{const g=new Game();g.start();g.enemies=[];g.direction('right');for(let i=0;i<8;i++)g.step();g.release();g.returnStep();const p={...g.player};g.acc=.8;g.direction('up');assert.equal(g.returning,false);assert.equal(g.acc,.8);g.update(.025);assert.equal(g.player.y,p.y-1);assert.equal(g.player.x,p.x);});
test('pause freezes return, resuming continues the retreat',()=>{const g=new Game();g.start();g.enemies=[];g.direction('right');for(let i=0;i<8;i++)g.step();g.release();g.pause();const p={...g.player};g.update(.05);assert.deepEqual(g.player,p);g.pause();g.update(.05);assert.ok(g.player.x<p.x);assert.equal(g.returning,true);});
test('hunter aims toward unfinished trail and speeds up',()=>{const g=new Game();g.start();g.direction('right');for(let i=0;i<8;i++)g.step();const e={x:20,y:45.5,vx:0,vy:1,kind:'hunter',phase:0,turnIn:0};g.steerEnemy(e,.01);assert.equal(e.hunting,true);assert.ok(e.vx<0);assert.ok(Math.abs(e.vy)<.001);assert.ok(Math.hypot(e.vx,e.vy)>10);});
test('roamer changes heading rather than repeating diagonal reflection',()=>{const g=new Game();g.start();const e={x:20,y:20,vx:4,vy:4,kind:'roamer',phase:0,turnIn:0};g.elapsed=1;g.steerEnemy(e,.01);assert.ok(Math.abs(e.vx-e.vy)>1);});
function remaining(g,n){g.grid.fill(SAFE);for(let i=0;i<n;i++)g.grid[i]=EMPTY;}
test('90 percent is inclusive and under 90 percent does not clear',()=>{const g=new Game();g.start();remaining(g,541);g.checkProgress();assert.equal(g.status,'playing');remaining(g,540);g.checkProgress();assert.equal(g.status,'clear');assert.equal(g.bonusUnlocked,false);assert.equal(g.target,90);});
test('90 percent clear can continue toward 95 percent without awarding clear twice',()=>{const g=new Game();g.start();remaining(g,540);g.checkProgress();const score=g.score;assert.equal(g.continueBonus(),true);assert.equal(g.status,'playing');assert.equal(g.target,95);g.checkProgress();assert.equal(g.status,'playing');assert.equal(g.score,score);remaining(g,271);g.checkProgress();assert.equal(g.bonusUnlocked,false);remaining(g,270);g.checkProgress();assert.equal(g.status,'clear');assert.equal(g.bonusUnlocked,true);assert.equal(g.score,score+5000);g.checkProgress();assert.equal(g.score,score+5000);assert.equal(g.continueBonus(),false);});
test('capture directly beyond 95 percent unlocks bonus without intermediate choice',()=>{const g=new Game();g.start();remaining(g,260);g.checkProgress();assert.equal(g.status,'clear');assert.equal(g.bonusUnlocked,true);assert.ok(g.score>=5000);assert.ok(g.events.some(e=>e.type==='bonus'));});
test('manual out and back retracts the final cell without gaining land, score or combo',()=>{const g=new Game();g.start();const area=g.area(),origin={...g.player};for(let attempt=0;attempt<10;attempt++){g.direction('right');for(let i=0;i<7;i++)g.step();g.direction('left');for(let i=0;i<7;i++)g.step();assert.deepEqual(g.player,origin);assert.equal(g.trail.length,0);assert.equal(g.area(),area);assert.equal(g.score,0);assert.equal(g.combo,0);assert.equal(g.lives,3);assert.equal(g.events.some(e=>e.type==='capture'),false);}});
test('a one-cell-wide strip closing at a different safe point is captured',()=>{const g=new Game();g.start();const area=g.area();g.direction('right');g.step();g.direction('up');for(let i=0;i<4;i++)g.step();g.direction('left');g.step();assert.equal(g.trail.length,0);assert.ok(g.area()>area);assert.ok(g.score>0);assert.equal(g.cell(2,43),SAFE);});
test('a real closed pocket on the same boundary still captures its interior',()=>{const g=new Game();g.start();const area=g.area();g.enemies=[{x:40,y:45,vx:0,vy:0}];g.direction('right');for(let i=0;i<6;i++)g.step();g.direction('up');for(let i=0;i<6;i++)g.step();g.direction('left');for(let i=0;i<6;i++)g.step();assert.ok(g.area()>area);assert.equal(g.cell(4,42),SAFE);assert.equal(g.cell(40,45),EMPTY);assert.ok(g.score>0);assert.equal(g.events.some(e=>e.type==='capture'),true);});
test('small closed block with no empty interior still gains exactly its six drawn cells',()=>{const g=new Game();g.start();const before=g.area();g.enemies=[{x:40,y:45,vx:0,vy:0}];g.direction('right');for(let i=0;i<3;i++)g.step();g.direction('up');g.step();g.direction('left');for(let i=0;i<3;i++)g.step();assert.equal(g.trail.length,0);for(const y of [44,45])for(let x=2;x<=4;x++)assert.equal(g.cell(x,y),SAFE);assert.ok(Math.abs(g.area()-before-6/(W*H)*100)<1e-10);assert.ok(g.score>0);});
test('a single cell joining two different safe points is captured',()=>{const g=new Game();g.start();g.player={x:1,y:2};g.lastSafe={...g.player};const before=g.area();g.direction('right');g.step();g.direction('up');g.step();assert.equal(g.cell(2,2),SAFE);assert.equal(g.trail.length,0);assert.ok(Math.abs(g.area()-before-1/(W*H)*100)<1e-10);assert.ok(g.score>0);});

test('enemy near a one-cell wall does not protect an empty pocket across it',()=>{const g=new Game();g.start();g.enemies=[{x:8.5,y:42.5,vx:0,vy:0}];g.direction('right');for(let i=0;i<6;i++)g.step();g.direction('up');for(let i=0;i<6;i++)g.step();g.direction('left');for(let i=0;i<6;i++)g.step();assert.equal(g.cell(6,42),SAFE);assert.equal(g.cell(8,42),EMPTY);});
test('ring containing an enemy is filled while the outer enemy region survives',()=>{const g=new Game();g.start();for(let y=40;y<=50;y++)for(let x=20;x<=30;x++)if(x===20||x===30||y===40||y===50)g.grid[g.index(x,y)]=SAFE;g.grid[g.index(20,45)]=TRAIL;g.trail=[{x:20,y:45}];g.enemies=[{x:25.5,y:45.5,vx:0,vy:0},{x:10.5,y:20.5,vx:0,vy:0}];g.capture();assert.equal(g.cell(25,45),SAFE);assert.equal(g.cell(10,20),EMPTY);for(const e of g.enemies)assert.equal(g.cell(Math.floor(e.x),Math.floor(e.y)),EMPTY);});
