// Execute the real UI script with a deterministic DOM/Canvas adapter.
// This verifies lifecycle logic; it does not claim to emulate a phone GPU.
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const P=require('../physics.js'),G=require('../graphics.js'),Matter=require('../vendor/matter.min.js');
async function harness({offline=false,storageBlocked=false}={}){
 let badImage=offline,badDraw=false,clock=100,serial=0;const frames=new Map(),nodes=new Map(),tools=new Map(),events={};
 const context=new Proxy({drawImage(){if(badDraw)throw Error('simulated GPU failure')}},{get:(o,k)=>o[k]??(()=>{})});
 class El{constructor(){this.children=[];this.events={};this.classList={add(){},remove(){},toggle(){}};this.hidden=false;this.open=false;this.textContent='';this.src=''}addEventListener(k,v){this.events[k]=v}setAttribute(){}replaceChildren(...c){this.children=c}append(...c){this.children.push(...c)}showModal(){this.open=true}close(){this.open=false}focus(){}getContext(){return context}getBoundingClientRect(){return{left:0,width:420}}setPointerCapture(){}releasePointerCapture(){}hasPointerCapture(){return true}}
 const el=id=>{if(!nodes.has(id))nodes.set(id,new El());return nodes.get(id)};
 const doc={getElementById:el,querySelector:el,querySelectorAll:()=>[],createElement:()=>new El(),hidden:false,addEventListener:(k,v)=>events[k]=v,modelContext:{registerTool:t=>tools.set(t.name,t)}};
 class Img{set src(url){this._src=url;queueMicrotask(()=>{if(badImage){this.onerror?.();return}this.complete=true;this.naturalWidth=256;this.naturalHeight=256;this.onload?.()})}get src(){return this._src}decode(){return Promise.resolve()}}
 const window={Matter,DuckPhysics:P,DuckGraphics:G,devicePixelRatio:1,addEventListener:(k,v)=>events[k]=v};
 const globals={document:doc,window,Matter,DuckPhysics:P,DuckGraphics:G,Image:Img,URLSearchParams,location:{search:''},matchMedia:()=>({matches:true}),localStorage:{getItem(){if(storageBlocked)throw Error('blocked');return null},setItem(){if(storageBlocked)throw Error('blocked')}},performance:{now:()=>clock},requestAnimationFrame:fn=>{frames.set(++serial,fn);return serial},cancelAnimationFrame:id=>frames.delete(id),console:{error(){}},setTimeout,clearTimeout};
 vm.runInNewContext(fs.readFileSync(require.resolve('../game.js'),'utf8'),globals);
 const flush=()=>new Promise(resolve=>setImmediate(resolve));await flush();
 return{el,doc,events,frames,tools,flush,setOffline:v=>badImage=v,setBadDraw:v=>badDraw=v,state:()=>tools.get('duck_game_state').execute(),drop:x=>tools.get('drop_duck').execute({x}),run(ms=1000){for(let n=0;n<Math.ceil(ms/16.667);n++){clock+=16.667;const batch=[...frames.values()];frames.clear();batch.forEach(fn=>fn(clock))}}};
}
test('actual UI starts once, loads eight sprites, and performs a scored merge',async()=>{const h=await harness();assert.equal(h.el('load').hidden,true);assert.equal(h.frames.size,1);h.drop(210);h.run(1000);h.drop(210);h.run(1800);assert.equal(h.state().score,30);assert.equal(h.frames.size,1);assert.equal(h.el('score').textContent,'30')});
test('storage disabled does not stop play',async()=>{const h=await harness({storageBlocked:true});h.drop(210);h.run(800);assert.equal(h.state().drops,1);assert.equal(h.el('load').hidden,true)});
test('render failure stops invisible physics; retry preserves score and positions',async()=>{const h=await harness();h.drop(210);h.run(1000);h.drop(210);h.run(1800);h.setBadDraw(true);h.run(20);const before=h.state();assert.equal(before.paused,true);assert.equal(h.frames.size,0);assert.equal(h.el('load').hidden,false);assert.throws(()=>h.drop(200));h.run(5000);assert.equal(h.state().time,before.time);h.setBadDraw(false);h.el('load').children[1].onclick();await h.flush();const after=h.state();assert.equal(after.score,before.score);assert.equal(JSON.stringify(after.ducks),JSON.stringify(before.ducks));assert.equal(after.paused,true);assert.equal(h.frames.size,1);h.el('modal-actions').children[0].onclick();assert.equal(h.state().paused,false)});
test('startup image failure can retry without creating duplicate worlds or loops',async()=>{const h=await harness({offline:true});assert.equal(h.tools.size,0);assert.equal(h.frames.size,0);h.setOffline(false);h.el('load').children[1].onclick();await h.flush();assert.equal(h.tools.size,2);assert.equal(h.frames.size,1);assert.equal(h.state().score,0)});
test('tab return and canvas restoration preserve game and coalesce reloads',async()=>{const h=await harness();h.drop(120);h.run(1000);const before=h.state();h.doc.hidden=true;h.events.visibilitychange();h.doc.hidden=false;h.events.visibilitychange();h.events.pageshow({persisted:true});await h.flush();assert.equal(h.state().score,before.score);assert.equal(JSON.stringify(h.state().ducks),JSON.stringify(before.ducks));assert.equal(h.frames.size,1);assert.equal(h.state().paused,true);h.el('board').events.contextlost({preventDefault(){}});assert.equal(h.frames.size,0);h.el('board').events.contextrestored();await h.flush();assert.equal(h.frames.size,1)});
test('cancelled or secondary touch cannot drop a duck',async()=>{const h=await harness(),b=h.el('board');const pointer={pointerId:1,isPrimary:true,pointerType:'touch',clientX:200,preventDefault(){}};b.events.pointerdown(pointer);b.events.pointercancel();b.events.pointerup(pointer);assert.equal(h.state().drops,0);b.events.pointerdown({...pointer,isPrimary:false});b.events.pointerup(pointer);assert.equal(h.state().drops,0);b.events.pointerdown(pointer);b.events.pointerup(pointer);assert.equal(h.state().drops,1)});
test('restart requires confirmation and resets only after confirm',async()=>{const h=await harness();h.drop(200);h.run(800);h.el('restart').onclick();assert.equal(h.state().drops,1);assert.equal(h.state().paused,true);h.el('modal-actions').children[1].onclick();assert.equal(h.state().drops,1);assert.equal(h.state().paused,false);h.el('restart').onclick();h.el('modal-actions').children[0].onclick();assert.equal(h.state().drops,0);assert.equal(h.state().score,0)});
