/* Duck Duck Merge — self-contained browser game. No account or remote scores. */
(()=>{'use strict';
 const $=id=>document.getElementById(id),canvas=$('board'),ctx=canvas.getContext('2d'),modal=$('modal');
 if(!ctx||!window.Matter||!window.DuckPhysics){$('load').textContent='게임을 불러오지 못했어요. 새로고침해 주세요.';return}
 const {Game,TIERS,WIDTH,HEIGHT,FLOOR,LINE,SPAWN,STEP,clamp}=DuckPhysics;
 let best=0,sound=false,ready=false,aim=WIDTH/2,activePointer=null,particles=[],last=0,acc=0,audio=null,toastUntil=0,modalKind='',game,images=[];
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 try{best=Math.max(0,Number(localStorage.getItem('duck-merge.best.v1'))||0);sound=localStorage.getItem('duck-merge.sound.v1')==='1'}catch{}
 $('best').textContent=best.toLocaleString('ko-KR');
 const atlas=new Image();atlas.src='assets/ducks.webp';
 // Sprite-atlas rendering: key the neutral matte connected to each cell edge.
 // The source artwork stays intact; enclosed white/cream faces are never keyed.
 function prepareSprites(source){const sw=source.width/4,sh=source.height/2;for(let tier=0;tier<8;tier++){
  const tile=document.createElement('canvas');tile.width=Math.floor(sw);tile.height=Math.floor(sh);const tc=tile.getContext('2d',{willReadFrequently:true});tc.drawImage(source,(tier%4)*sw,Math.floor(tier/4)*sh,sw,sh,0,0,tile.width,tile.height);
  const {width:w,height:h}=tile,data=tc.getImageData(0,0,w,h),px=data.data,seen=new Uint8Array(w*h),queue=new Int32Array(w*h);let tail=0,head=0;
  const neutral=i=>{const j=i*4,r=px[j],g=px[j+1],b=px[j+2];return px[j+3]<32||(Math.min(r,g,b)>145&&Math.max(r,g,b)-Math.min(r,g,b)<36)};
  const push=i=>{if(i>=0&&i<w*h&&!seen[i]&&neutral(i)){seen[i]=1;queue[tail++]=i}};
  for(let x=0;x<w;x++){push(x);push((h-1)*w+x)}for(let y=0;y<h;y++){push(y*w);push(y*w+w-1)}
  while(head<tail){const i=queue[head++],x=i%w;px[i*4+3]=0;if(x>0)push(i-1);if(x<w-1)push(i+1);push(i-w);push(i+w)}
  let x0=w,y0=h,x1=0,y1=0;for(let y=0;y<h;y++)for(let x=0;x<w;x++){if(px[(y*w+x)*4+3]>32){x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y)}}
  if(x1<=x0||y1<=y0)throw Error('Empty duck sprite');tc.putImageData(data,0,0);
  const sprite=document.createElement('canvas');sprite.width=256;sprite.height=256;const sc=sprite.getContext('2d');const bw=x1-x0+1,bh=y1-y0+1,scale=244/Math.max(bw,bh);sc.drawImage(tile,x0,y0,bw,bh,(256-bw*scale)/2,(256-bh*scale)/2,bw*scale,bh*scale);images.push(sprite);
 }
 }
 function imgUrl(tier){return images[tier].toDataURL('image/png')}
 function update(){if(!game)return;$('score').textContent=game.score.toLocaleString('ko-KR');$('next').src=imgUrl(game.next);$('next').alt='다음: '+TIERS[game.next].name+' 오리';$('empty-hint').hidden=game.dropCount>0;$('unlocked-count').textContent=(game.highest+1)+' / 8';document.querySelectorAll('.duck-card').forEach((el,i)=>{el.classList.toggle('reached',i<=game.highest);el.classList.toggle('current',i===game.highest)});if(game.score>best){best=game.score;$('best').textContent=best.toLocaleString('ko-KR');try{localStorage.setItem('duck-merge.best.v1',String(best))}catch{}}}
 function beep(tier=0,drop=false){if(!sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')void audio.resume();const now=audio.currentTime,osc=audio.createOscillator(),gain=audio.createGain();osc.type=drop?'sine':'triangle';osc.frequency.setValueAtTime(drop?500:480+tier*70,now);osc.frequency.exponentialRampToValueAtTime(drop?220:850+tier*80,now+.1);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.055,now+.015);gain.gain.exponentialRampToValueAtTime(.0001,now+.16);osc.connect(gain);gain.connect(audio.destination);osc.start(now);osc.stop(now+.18)}catch{}}
 function toast(text){$('toast').textContent=text;$('toast').classList.add('show');toastUntil=performance.now()+1800}
 function event(e){if(e.type==='drop'){beep(0,true);update()}if(e.type==='merge'){update();beep(e.tier);$('status').textContent=TIERS[e.tier].name+' 오리 합체! '+game.score+'점';if(!reduced){for(let i=0;i<12;i++){const a=Math.PI*2*i/12;particles.push({x:e.x,y:e.y,vx:Math.cos(a)*(1+Math.random()*2),vy:Math.sin(a)*(1+Math.random()*2),life:1,color:i%2?'#fff':'#ffc94e',text:null})}particles.push({x:e.x,y:e.y-20,vx:0,vy:-.7,life:1,color:'#3689cd',text:'+'+e.points})}if(e.tier===7)toast('대왕 오리 완성! +500');else if(e.tier>=5)toast(TIERS[e.tier].name+' 오리 등장!')}if(e.type==='over'){activePointer=null;const error=e.reason==='error';openModal(error?'잠깐, 오리가 길을 잃었어요':'오늘도 잘 놀았다, 꽥!',error?'새 판으로 다시 시작해 주세요.':game.score.toLocaleString('ko-KR')+'점 · '+TIERS[game.highest].name+' 오리까지 만났어요!\n최고 점수 '+best.toLocaleString('ko-KR')+'점',[{label:'한 판 더 하기',primary:true,action:restart}],game.highest,'over')}}
 function openModal(title,text,actions,tier=1,kind='pause'){game.paused=true;activePointer=null;modalKind=kind;$('modal-title').textContent=title;$('modal-text').textContent=text;$('modal-duck').src=imgUrl(tier);$('modal-actions').replaceChildren();for(const action of actions){const b=document.createElement('button');b.textContent=action.label;if(action.primary)b.className='primary';b.onclick=action.action;$('modal-actions').append(b)}if(!modal.open)modal.showModal();$('pause').setAttribute('aria-label','게임 계속하기');$('pause').textContent='▶'}
 function resume(){if(game.over)return;modal.close();game.paused=false;last=0;acc=0;activePointer=null;$('pause').setAttribute('aria-label','일시정지');$('pause').textContent='Ⅱ';canvas.focus({preventScroll:true})}
 function pause(){if(!ready||game.over)return;openModal('잠깐 쉬어가요','오리들이 얌전히 기다리고 있어요.',[{label:'계속하기',primary:true,action:resume}],1,'pause')}
 function restart(){modal.close();game.reset();particles=[];acc=0;last=0;aim=WIDTH/2;activePointer=null;$('danger').hidden=true;$('toast').classList.remove('show');$('pause').textContent='Ⅱ';$('pause').setAttribute('aria-label','일시정지');update();$('status').textContent='새 게임을 시작했어요.';canvas.focus({preventScroll:true})}
 function confirmRestart(){if(!ready)return;if(game.dropCount===0){restart();return}openModal('새 판으로 시작할까요?','현재 판은 끝나고, 최고 기록은 남아요.',[{label:'새로 시작',primary:true,action:restart},{label:'이어서 하기',action:resume}],0,'restart')}
 function help(){if(!ready||game.over)return;openModal('같이 굴러볼까?','손가락으로 좌우 이동 후 놓으면 낙하!\n같은 오리 둘이 닿으면 다음 단계로 합체해요.\n빨간 선 위에 3초 머무르면 게임이 끝나요.\n\nPC: ← → 이동 · 스페이스로 놓기 · P 일시정지\n대왕 오리는 합체하지 않고 남아요.',[{label:'알겠어, 꽥!',primary:true,action:resume}],2,'help')}
 modal.addEventListener('cancel',e=>{e.preventDefault();if(!game.over)resume()});
 function resize(){const dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(WIDTH*dpr);canvas.height=Math.round(HEIGHT*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
 function sprite(tier,x,y,r,angle=0,alpha=1){ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.globalAlpha=alpha;ctx.drawImage(images[tier],-r*1.05,-r*1.05,r*2.1,r*2.1);ctx.restore()}
 function render(now){ctx.clearRect(0,0,WIDTH,HEIGHT);
  ctx.save();ctx.strokeStyle='#ffffff48';ctx.lineWidth=1;for(let x=21;x<WIDTH;x+=28){for(let y=135;y<FLOOR;y+=28){ctx.beginPath();ctx.arc(x,y,.7,0,Math.PI*2);ctx.stroke()}}ctx.restore();
  ctx.fillStyle='#b0ddfa88';ctx.fillRect(0,FLOOR,WIDTH,HEIGHT-FLOOR);ctx.strokeStyle='#f78787';ctx.lineWidth=2.5;ctx.setLineDash([8,9]);ctx.beginPath();ctx.moveTo(10,LINE);ctx.lineTo(WIDTH-10,LINE);ctx.stroke();ctx.setLineDash([]);
  if(!game.over){const r=TIERS[game.current].r;aim=clamp(aim,r+5,WIDTH-r-5);let landing=FLOOR-r;for(const b of game.ducks){const dx=aim-b.position.x,rr=r+TIERS[b.duck.tier].r;if(Math.abs(dx)<rr){const candidate=b.position.y-Math.sqrt(rr*rr-dx*dx);if(candidate>SPAWN)landing=Math.min(landing,candidate)}}ctx.strokeStyle='#69b4ed99';ctx.lineWidth=2;ctx.setLineDash([4,8]);ctx.beginPath();ctx.moveTo(aim,SPAWN+r+5);ctx.lineTo(aim,landing);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.arc(aim,landing,3,0,Math.PI*2);ctx.fillStyle='#8bc8ee';ctx.fill();sprite(game.current,aim,SPAWN,r,0,game.time<game.cooldown?.38:1)}
  for(const b of game.ducks){const r=TIERS[b.duck.tier].r;const age=game.time-b.duck.born;const pop=reduced?1:1+Math.sin(clamp(age/210,0,1)*Math.PI)*.08;sprite(b.duck.tier,b.position.x,b.position.y,r*pop,b.angle)}
  if(!game.paused&&!game.over){const frameDelta=Math.min(now-(render.previous||now),40)/16.667;for(const p of particles){p.x+=p.vx*frameDelta;p.y+=p.vy*frameDelta;p.life-=.025*frameDelta}particles=particles.filter(p=>p.life>0)}render.previous=now;
  for(const p of particles){ctx.save();ctx.globalAlpha=p.life;ctx.fillStyle=p.color;if(p.text){ctx.font='bold 20px sans-serif';ctx.textAlign='center';ctx.fillText(p.text,p.x,p.y)}else{ctx.translate(p.x,p.y);ctx.rotate(p.life*3);ctx.fillRect(-2,-2,4,4)}ctx.restore()}
  $('danger').hidden=game.warn<200||game.over;if(game.warn>0)$('countdown').textContent=String(Math.max(1,Math.ceil((3000-game.warn)/1000)));
  if(toastUntil&&now>toastUntil){$('toast').classList.remove('show');toastUntil=0}
 }
 function frame(now){if(!ready)return;const elapsed=last?Math.min(now-last,65):0;last=now;if(!game.paused&&!game.over){acc+=elapsed;let steps=0;while(acc>=STEP&&steps++<8){game.step(STEP);acc-=STEP;if(game.over)break}}else acc=0;render(now);requestAnimationFrame(frame)}
 const canPlay=()=>ready&&!game.over&&!game.paused&&!modal.open;
 function point(e){const rect=canvas.getBoundingClientRect();aim=clamp((e.clientX-rect.left)/rect.width*WIDTH,5,WIDTH-5)}
 canvas.addEventListener('pointerdown',e=>{if(!canPlay()||activePointer!==null||!e.isPrimary||(e.pointerType==='mouse'&&e.button!==0))return;e.preventDefault();activePointer=e.pointerId;point(e);canvas.setPointerCapture(e.pointerId);canvas.focus({preventScroll:true})});
 canvas.addEventListener('pointermove',e=>{if(!canPlay())return;if(activePointer===e.pointerId||(e.pointerType==='mouse'&&activePointer===null))point(e)});
 canvas.addEventListener('pointerup',e=>{if(e.pointerId!==activePointer)return;point(e);activePointer=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);if(canPlay())game.drop(aim)});
 canvas.addEventListener('pointercancel',()=>{activePointer=null});canvas.addEventListener('lostpointercapture',()=>{activePointer=null});
 canvas.addEventListener('keydown',e=>{if(!canPlay())return;if(['ArrowLeft','ArrowRight',' ','Enter'].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')aim-=12;if(e.key==='ArrowRight')aim+=12;if((e.key===' '||e.key==='Enter')&&!e.repeat)game.drop(aim);if(e.key.toLowerCase()==='p')pause()});
 $('pause').onclick=()=>game?.paused?resume():pause();$('restart').onclick=confirmRestart;$('help').onclick=help;
 function soundUI(){$('sound').setAttribute('aria-pressed',String(sound));$('sound').setAttribute('aria-label',sound?'소리 끄기':'소리 켜기')};soundUI();$('sound').onclick=()=>{sound=!sound;soundUI();try{localStorage.setItem('duck-merge.sound.v1',sound?'1':'0')}catch{}if(sound)beep(2)};
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&canPlay())pause();last=0;acc=0});window.addEventListener('resize',resize);
 // Same actions as the visible interface, without privileged test mutations.
 function registerTools(){const mc=document.modelContext;if(!mc?.registerTool)return;const definitions=[{name:'duck_game_state',description:'Read the current local duck merge game and duck positions.',annotations:{readOnlyHint:true},inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>game.snapshot()},{name:'drop_duck',description:'Drop the current duck at horizontal position x (0–420). Uses the same cooldown as the game board.',inputSchema:{type:'object',properties:{x:{type:'number',minimum:0,maximum:420}},required:['x'],additionalProperties:false},execute:input=>{if(!input||!Number.isFinite(input.x)||input.x<0||input.x>420)throw Error('x must be between 0 and 420');if(!canPlay())throw Error('Game is paused or finished');aim=input.x;const accepted=game.drop(aim);return{accepted,...game.snapshot()}}}];for(const def of definitions){try{Promise.resolve(mc.registerTool(def)).catch(()=>{})}catch{}}}
 function fail(){ready=false;$('load').hidden=false;$('load').textContent='오리 그림을 불러오지 못했어요.\n인터넷 연결을 확인하고 새로고침해 주세요.';$('pause').disabled=true;$('restart').disabled=true}
 atlas.onload=()=>{try{prepareSprites(atlas);document.querySelector('.brand img').src=imgUrl(1);document.querySelector('.goal img').src=imgUrl(7);document.querySelector('link[rel=icon]').href=imgUrl(0);$('duck-grid').innerHTML=TIERS.map((t,i)=>'<div class="duck-card" title="'+(i+1)+'단계 '+t.name+' 오리"><img src="'+imgUrl(i)+'" alt="'+t.name+' 오리" width="70" height="70"><span><i>'+(i+1)+'</i>'+t.name+'</span></div>').join('');game=new Game({onEvent:event});ready=true;resize();update();$('load').hidden=true;$('status').textContent='준비 완료. 첫 오리를 놓아보세요.';registerTools();requestAnimationFrame(frame)}catch(e){console.error('Duck initialization failed',e);fail()}};atlas.onerror=fail;if(atlas.complete&&atlas.naturalWidth)atlas.onload();
})();
