/* Duck Duck Merge — self-contained browser game. No account or remote scores. */
(()=>{'use strict';
 const $=id=>document.getElementById(id),canvas=$('board'),ctx=canvas.getContext('2d'),modal=$('modal');
 if(!ctx||!window.Matter||!window.DuckPhysics||!window.DuckGraphics){$('load').textContent='게임을 불러오지 못했어요. 새로고침해 주세요.';return}
 const {Game,TIERS,FINAL_TIER,WIDTH,HEIGHT,FLOOR,LINE,SPAWN,STEP,clamp}=DuckPhysics;
 let best=0,completions=0,sound=false,ready=false,aim=WIDTH/2,activePointer=null,particles=[],last=0,acc=0,audio=null,toastUntil=0,modalKind='',game,images=[],raf=0,recovering=null;
 const debug=new URLSearchParams(location.search).get('debug')==='1';
 const assets=DuckGraphics.createAssetStore(url=>new Promise((resolve,reject)=>{const img=new Image();const timer=setTimeout(()=>reject(Error('Image timeout')),12000);img.onload=async()=>{try{if(img.decode)await img.decode();clearTimeout(timer);resolve(img)}catch(e){clearTimeout(timer);reject(e)}};img.onerror=()=>{clearTimeout(timer);reject(Error('Duck image load failed'))};img.src=url;}));
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 try{best=Math.max(0,Number(localStorage.getItem('duck-merge.best.v1'))||0);completions=Math.max(0,Number(localStorage.getItem('duck-merge.completions.v1'))||0);sound=localStorage.getItem('duck-merge.sound.v1')==='1'}catch{}
 $('best').textContent=best.toLocaleString('ko-KR');
 function imgUrl(tier){return images[tier]?.src||DuckGraphics.urls[tier]}
 function update(){if(!game)return;$('score').textContent=game.score.toLocaleString('ko-KR');$('next').src=imgUrl(game.next);$('next').alt='다음: '+TIERS[game.next].name+' 오리';$('empty-hint').hidden=game.dropCount>0;$('unlocked-count').textContent=(game.highest+1)+' / '+TIERS.length;$('completion-count').textContent=completions.toLocaleString('ko-KR');document.querySelectorAll('.duck-card').forEach((el,i)=>{el.classList.toggle('reached',i<=game.highest);el.classList.toggle('current',i===game.highest)});if(game.score>best){best=game.score;$('best').textContent=best.toLocaleString('ko-KR');try{localStorage.setItem('duck-merge.best.v1',String(best))}catch{}}}
 function beep(tier=0,drop=false){if(!sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')void audio.resume();const now=audio.currentTime,osc=audio.createOscillator(),gain=audio.createGain();osc.type=drop?'sine':'triangle';osc.frequency.setValueAtTime(drop?500:480+tier*70,now);osc.frequency.exponentialRampToValueAtTime(drop?220:850+tier*80,now+.1);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.055,now+.015);gain.gain.exponentialRampToValueAtTime(.0001,now+.16);osc.connect(gain);gain.connect(audio.destination);osc.start(now);osc.stop(now+.18)}catch{}}
 function toast(text){$('toast').textContent=text;$('toast').classList.add('show');toastUntil=performance.now()+1800}
 function celebrateFinal(){completions++;try{localStorage.setItem('duck-merge.completions.v1',String(completions))}catch{}update();openModal('전설의 태양 오리 완성!',game.score.toLocaleString('ko-KR')+'점 · 최종 완성 '+completions.toLocaleString('ko-KR')+'회\n최고 기록과 완성 횟수가 저장됐어요.',[{label:'기록 저장',primary:true,action:finishVictory},{label:'계속 플레이',action:resume}],FINAL_TIER,'victory')}
 function event(e){if(e.type==='drop'){beep(0,true);update()}if(e.type==='merge'){update();beep(e.tier);$('status').textContent=TIERS[e.tier].name+' 오리 합체! '+game.score+'점';if(!reduced){const count=e.final?36:12;for(let i=0;i<count;i++){const a=Math.PI*2*i/count;particles.push({x:e.x,y:e.y,vx:Math.cos(a)*(1+Math.random()*3),vy:Math.sin(a)*(1+Math.random()*3),life:1,color:i%3?'#ffc94e':'#fff',text:null})}particles.push({x:e.x,y:e.y-20,vx:0,vy:-.7,life:1,color:'#3689cd',text:'+'+e.points})}if(e.final)celebrateFinal();else if(e.tier===7)toast('대왕 오리 등장! +500');else if(e.tier>=5)toast(TIERS[e.tier].name+' 오리 등장!')}if(e.type==='over'){activePointer=null;const error=e.reason==='error',victory=e.reason==='victory';openModal(error?'잠깐, 오리가 길을 잃었어요':victory?'기록 저장 완료!':'오늘도 잘 놀았다, 꽥!',error?'새 판으로 다시 시작해 주세요.':game.score.toLocaleString('ko-KR')+'점 · '+TIERS[game.highest].name+' 오리까지 만났어요!\n최고 점수 '+best.toLocaleString('ko-KR')+'점',[{label:'한 판 더 하기',primary:true,action:restart}],game.highest,victory?'victory':'over')}}
 function openModal(title,text,actions,tier=1,kind='pause'){game.paused=true;activePointer=null;modalKind=kind;modal.classList.toggle('victory',kind==='victory');$('modal-title').textContent=title;$('modal-text').textContent=text;$('modal-duck').src=imgUrl(tier);$('modal-actions').replaceChildren();for(const action of actions){const b=document.createElement('button');b.textContent=action.label;if(action.primary)b.className='primary';b.onclick=action.action;$('modal-actions').append(b)}if(!modal.open)modal.showModal();$('pause').setAttribute('aria-label','게임 계속하기');$('pause').textContent='▶'}
 function finishVictory(){if(!game||game.over)return;game.finish('victory')}
 function resume(){if(!ready||game.over)return;modal.close();game.paused=false;last=0;acc=0;activePointer=null;$('pause').setAttribute('aria-label','일시정지');$('pause').textContent='Ⅱ';canvas.focus({preventScroll:true})}
 function pause(){if(!ready||game.over)return;openModal('잠깐 쉬어가요','오리들이 얌전히 기다리고 있어요.',[{label:'계속하기',primary:true,action:resume}],1,'pause')}
 function restart(){if(!ready)return;modal.close();game.reset();particles=[];acc=0;last=0;aim=WIDTH/2;activePointer=null;$('danger').hidden=true;$('toast').classList.remove('show');$('pause').textContent='Ⅱ';$('pause').setAttribute('aria-label','일시정지');update();$('status').textContent='새 게임을 시작했어요.';canvas.focus({preventScroll:true})}
 function confirmRestart(){if(!ready)return;if(game.dropCount===0){restart();return}openModal('새 판으로 시작할까요?','현재 판은 끝나고, 최고 기록은 남아요.',[{label:'새로 시작',primary:true,action:restart},{label:'이어서 하기',action:resume}],0,'restart')}
 function help(){if(!ready||game.over)return;openModal('같이 굴러볼까?','손가락으로 좌우 이동 후 놓으면 낙하!\n같은 오리 둘이 닿으면 다음 단계로 합체해요.\n빨간 선 위에 3초 머무르면 게임이 끝나요.\n\nPC: ← → 이동 · 스페이스로 놓기 · P 일시정지\n전설의 태양 오리를 만들면 성공이에요!',[{label:'알겠어, 꽥!',primary:true,action:resume}],2,'help')}
 modal.addEventListener('cancel',e=>{e.preventDefault();if(!game.over)resume()});
 function resize(){const dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(WIDTH*dpr);canvas.height=Math.round(HEIGHT*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
 function sprite(tier,x,y,r,angle=0,alpha=1){const im=images[tier];if(!im?.complete||!im.naturalWidth)throw Error('Duck image unavailable');const p=DuckGraphics.placement(tier,r);ctx.save();try{ctx.translate(x,y);ctx.rotate(angle);ctx.globalAlpha=alpha;ctx.drawImage(im,p.x,p.y,p.w,p.h);if(debug){ctx.strokeStyle='#e04768';ctx.lineWidth=1;ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.stroke()}}finally{ctx.restore()}}
 function render(now){if(ctx.isContextLost?.())throw Error('Canvas context unavailable');ctx.clearRect(0,0,WIDTH,HEIGHT);
  ctx.save();ctx.strokeStyle='#ffffff48';ctx.lineWidth=1;for(let x=21;x<WIDTH;x+=28){for(let y=135;y<FLOOR;y+=28){ctx.beginPath();ctx.arc(x,y,.7,0,Math.PI*2);ctx.stroke()}}ctx.restore();
  ctx.fillStyle='#b0ddfa88';ctx.fillRect(0,FLOOR,WIDTH,HEIGHT-FLOOR);ctx.strokeStyle='#f78787';ctx.lineWidth=2.5;ctx.setLineDash([8,9]);ctx.beginPath();ctx.moveTo(10,LINE);ctx.lineTo(WIDTH-10,LINE);ctx.stroke();ctx.setLineDash([]);
  if(!game.over){const r=TIERS[game.current].r;aim=clamp(aim,r+5,WIDTH-r-5);let landing=FLOOR-r;for(const b of game.ducks){const dx=aim-b.position.x,rr=r+TIERS[b.duck.tier].r;if(Math.abs(dx)<rr){const candidate=b.position.y-Math.sqrt(rr*rr-dx*dx);if(candidate>SPAWN)landing=Math.min(landing,candidate)}}ctx.strokeStyle='#69b4ed99';ctx.lineWidth=2;ctx.setLineDash([4,8]);ctx.beginPath();ctx.moveTo(aim,SPAWN+r+5);ctx.lineTo(aim,landing);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.arc(aim,landing,3,0,Math.PI*2);ctx.fillStyle='#8bc8ee';ctx.fill();sprite(game.current,aim,SPAWN,r,0,game.time<game.cooldown?.38:1)}
  for(const b of [...game.ducks].sort((a,b)=>a.position.y-b.position.y)){const r=TIERS[b.duck.tier].r;const age=game.time-b.duck.born;const pop=reduced?1:1+Math.sin(clamp(age/210,0,1)*Math.PI)*.08;sprite(b.duck.tier,b.position.x,b.position.y,r*pop,b.angle)}
  if(!game.paused&&!game.over){const frameDelta=Math.min(now-(render.previous||now),40)/16.667;for(const p of particles){p.x+=p.vx*frameDelta;p.y+=p.vy*frameDelta;p.life-=.025*frameDelta}particles=particles.filter(p=>p.life>0)}render.previous=now;
  for(const p of particles){ctx.save();ctx.globalAlpha=p.life;ctx.fillStyle=p.color;if(p.text){ctx.font='bold 20px sans-serif';ctx.textAlign='center';ctx.fillText(p.text,p.x,p.y)}else{ctx.translate(p.x,p.y);ctx.rotate(p.life*3);ctx.fillRect(-2,-2,4,4)}ctx.restore()}
  $('danger').hidden=game.warn<200||game.over;if(game.warn>0)$('countdown').textContent=String(Math.max(1,Math.ceil((3000-game.warn)/1000)));
  if(toastUntil&&now>toastUntil){$('toast').classList.remove('show');toastUntil=0}
 }
 function frame(now){raf=0;if(!ready)return;const ok=DuckGraphics.guardedFrame(game,()=>{const elapsed=last?Math.min(now-last,65):0;last=now;if(!game.paused&&!game.over){acc+=elapsed;let steps=0;while(acc>=STEP&&steps++<8){game.step(STEP);acc-=STEP;if(game.over)break}}else acc=0},()=>render(now),visualFailure);if(ok)raf=requestAnimationFrame(frame)}
 const canPlay=()=>ready&&!game.over&&!game.paused&&!modal.open;
 function point(e){const rect=canvas.getBoundingClientRect();aim=clamp((e.clientX-rect.left)/rect.width*WIDTH,5,WIDTH-5)}
 canvas.addEventListener('pointerdown',e=>{if(!canPlay()||activePointer!==null||!e.isPrimary||(e.pointerType==='mouse'&&e.button!==0))return;e.preventDefault();activePointer=e.pointerId;point(e);canvas.setPointerCapture(e.pointerId);canvas.focus({preventScroll:true})});
 canvas.addEventListener('pointermove',e=>{if(!canPlay())return;if(activePointer===e.pointerId||(e.pointerType==='mouse'&&activePointer===null))point(e)});
 canvas.addEventListener('pointerup',e=>{if(e.pointerId!==activePointer)return;point(e);activePointer=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);if(canPlay())game.drop(aim)});
 canvas.addEventListener('pointercancel',()=>{activePointer=null});canvas.addEventListener('lostpointercapture',()=>{activePointer=null});
 canvas.addEventListener('keydown',e=>{if(!canPlay())return;if(['ArrowLeft','ArrowRight',' ','Enter'].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')aim-=12;if(e.key==='ArrowRight')aim+=12;if((e.key===' '||e.key==='Enter')&&!e.repeat)game.drop(aim);if(e.key.toLowerCase()==='p')pause()});
 $('pause').onclick=()=>game?.paused?resume():pause();$('restart').onclick=confirmRestart;$('help').onclick=help;
 function soundUI(){$('sound').setAttribute('aria-pressed',String(sound));$('sound').setAttribute('aria-label',sound?'소리 끄기':'소리 켜기')};soundUI();$('sound').onclick=()=>{sound=!sound;soundUI();try{localStorage.setItem('duck-merge.sound.v1',sound?'1':'0')}catch{}if(sound)beep(2)};
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&canPlay())pause();else if(!document.hidden&&game)void recoverImages(true);last=0;acc=0});window.addEventListener('resize',resize);window.addEventListener('pageshow',e=>{if(e.persisted&&game)void recoverImages(true)});canvas.addEventListener('contextlost',e=>{e.preventDefault();visualFailure(Error('Canvas context lost'))});canvas.addEventListener('contextrestored',()=>{void recoverImages(true)});
 // Same actions as the visible interface, without privileged test mutations.
 function registerTools(){const mc=document.modelContext;if(!mc?.registerTool)return;const definitions=[{name:'duck_game_state',description:'Read the current local duck merge game and duck positions.',annotations:{readOnlyHint:true},inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>game.snapshot()},{name:'drop_duck',description:'Drop the current duck at horizontal position x (0–420). Uses the same cooldown as the game board.',inputSchema:{type:'object',properties:{x:{type:'number',minimum:0,maximum:420}},required:['x'],additionalProperties:false},execute:input=>{if(!input||!Number.isFinite(input.x)||input.x<0||input.x>420)throw Error('x must be between 0 and 420');if(!canPlay())throw Error('Game is paused or finished');aim=input.x;const accepted=game.drop(aim);return{accepted,...game.snapshot()}}}];for(const def of definitions){try{Promise.resolve(mc.registerTool(def)).catch(()=>{})}catch{}}}
 function visualFailure(error){ready=false;if(game)game.paused=true;activePointer=null;acc=0;last=0;if(raf){cancelAnimationFrame(raf);raf=0}if(modal.open)modal.close();console.error('Duck display paused',error);$('load').hidden=false;$('load').replaceChildren();const message=document.createElement('span');message.textContent=game?'그림을 다시 불러올게요. 점수와 오리는 그대로예요.':'오리 그림을 불러오지 못했어요.';const retry=document.createElement('button');retry.textContent='그림 다시 불러오기';retry.className='restart';retry.onclick=()=>{void recoverImages(true)};$('load').append(message,retry);$('status').textContent='그림 표시 오류로 일시정지했어요.';}
 function wireImages(){document.querySelector('.brand img').src=imgUrl(1);document.querySelector('.goal img').src=imgUrl(FINAL_TIER);document.querySelector('link[rel=icon]').href=imgUrl(0);$('duck-grid').innerHTML=TIERS.map((t,i)=>'<div class="duck-card" title="'+(i+1)+'단계 '+t.name+' 오리"><img src="'+imgUrl(i)+'" alt="'+t.name+' 오리" width="70" height="70"><span><i>'+(i+1)+'</i>'+t.name+'</span></div>').join('');}
 function recoverImages(force=false){if(recovering)return recovering;const existing=!!game;if(game)game.paused=true;ready=false;activePointer=null;if(raf){cancelAnimationFrame(raf);raf=0}$('load').hidden=false;$('load').textContent='오리 그림을 불러오는 중…';
  recovering=(async()=>{try{const loaded=await assets.load(force);images=loaded;wireImages();if(!game){game=new Game({onEvent:event});registerTools()}resize();update();render(performance.now());ready=true;$('load').hidden=true;acc=0;last=0;
   if(existing){if(game.over)event({type:'over',reason:'full'});else openModal('오리들이 돌아왔어요','점수와 배치를 그대로 유지했어요.',[{label:'계속하기',primary:true,action:resume}],1,'pause')}
   else $('status').textContent='준비 완료. 첫 오리를 놓아보세요.';
   if(!raf)raf=requestAnimationFrame(frame);
  }catch(error){visualFailure(error)}finally{recovering=null}})();return recovering;
 }
 void recoverImages();
})();
