(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./vendor/matter.min.js'));else root.DuckPhysics=factory(root.Matter)})(typeof globalThis!=='undefined'?globalThis:this,function(Matter){
 'use strict';
 const WIDTH=420,HEIGHT=580,FLOOR=568,LINE=105,SPAWN=45,STEP=1000/120,CONTACT_EPSILON=1.5;
 const TIERS=[{name:'아기',r:18,points:0},{name:'기본',r:25,points:30},{name:'리본',r:33,points:60},{name:'탐험가',r:42,points:100},{name:'마법사',r:53,points:150},{name:'천사',r:66,points:210},{name:'우주',r:80,points:280},{name:'대왕',r:96,points:500},{name:'황제',r:102,points:800},{name:'전설의 태양',r:110,points:1200}];
 const FINAL_TIER=TIERS.length-1;
 const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
 class Game{
 constructor(opts={}){this.random=opts.random||Math.random;this.onEvent=opts.onEvent||(()=>{});this.reset()}
 reset(){if(this.engine){Matter.Events.off(this.engine);Matter.Engine.clear(this.engine)}this.engine=Matter.Engine.create({enableSleeping:false,positionIterations:12,velocityIterations:10,constraintIterations:4});this.engine.gravity.y=1.25;this.time=0;this.score=0;this.highest=0;this.dropCount=0;this.merges=0;this.cooldown=0;this.over=false;this.paused=false;this.warn=0;this.current=0;this.next=0;this.ducks=[];
 const walls=[Matter.Bodies.rectangle(-28,HEIGHT/2,64,HEIGHT*3,{isStatic:true,friction:.35}),Matter.Bodies.rectangle(WIDTH+28,HEIGHT/2,64,HEIGHT*3,{isStatic:true,friction:.35}),Matter.Bodies.rectangle(WIDTH/2,FLOOR+30,WIDTH+128,60,{isStatic:true,friction:.45})];Matter.Composite.add(this.engine.world,walls)}
 choose(){const v=this.random();return v<.45?0:v<.77?1:v<.95?2:3}
 add(tier,x,y,options={}){if(!Number.isInteger(tier)||tier<0||tier>=TIERS.length||!Number.isFinite(x)||!Number.isFinite(y))throw new RangeError('Invalid duck');const r=TIERS[tier].r;const b=Matter.Bodies.circle(clamp(x,r+5,WIDTH-r-5),y,r,{restitution:.14,friction:.4,frictionStatic:.55,frictionAir:.008,density:.0018,slop:.01});b.duck={tier,born:this.time,grace:options.grace??1800,warning:0};if(options.angle)Matter.Body.setAngle(b,options.angle);Matter.Composite.add(this.engine.world,b);this.ducks.push(b);return b}
 drop(x){if(!Number.isFinite(x)||this.paused||this.over||this.time<this.cooldown)return false;const b=this.add(this.current,x,SPAWN);Matter.Body.setVelocity(b,{x:0,y:1});this.dropCount++;this.current=this.next;this.next=this.choose();this.cooldown=this.time+650;this.onEvent({type:'drop',body:b});return true}
 step(dt=STEP){if(this.paused||this.over)return;if(!Number.isFinite(dt)||dt<=0||dt>1000/30)throw new RangeError('Invalid physics timestep');for(const b of this.ducks)if(b.isSleeping)Matter.Sleeping.set(b,false);this.time+=dt;Matter.Engine.update(this.engine,dt);this.resolveMerges();this.warn=0;for(const b of this.ducks){if(!Number.isFinite(b.position.x)||!Number.isFinite(b.position.y)){this.finish('error');return}const above=b.position.y-TIERS[b.duck.tier].r<LINE;const eligible=this.time-b.duck.born>=b.duck.grace;if(above&&eligible)b.duck.warning+=dt;else b.duck.warning=0;this.warn=Math.max(this.warn,b.duck.warning)}if(this.warn>=3000||this.ducks.length>=180)this.finish('full')}
 resolveMerges(){const used=new Set();const alive=new Set(this.ducks);const queue=[];
 // Re-check actual circular contact every step. The tiny tolerance is below
 // one CSS pixel on common phones, covering solver slop without remote merges.
 const ordered=[...this.ducks].sort((a,b)=>a.position.x-b.position.x);
 for(let i=0;i<ordered.length;i++){const a=ordered[i];if(a.duck.tier>=FINAL_TIER)continue;const limit=TIERS[a.duck.tier].r*2+CONTACT_EPSILON;for(let j=i+1;j<ordered.length;j++){const b=ordered[j];if(b.position.x-a.position.x>limit)break;if(a.duck.tier!==b.duck.tier)continue;if(Math.hypot(a.position.x-b.position.x,a.position.y-b.position.y)<=limit)queue.push([a,b]);}}
for(const[a,b]of queue){if(used.has(a)||used.has(b)||!alive.has(a)||!alive.has(b)||!a.duck||!b.duck||a.duck.tier!==b.duck.tier||a.duck.tier>=FINAL_TIER)continue;if(this.time-a.duck.born<110||this.time-b.duck.born<110)continue;used.add(a);used.add(b);const tier=a.duck.tier+1,r=TIERS[tier].r,x=clamp((a.position.x+b.position.x)/2,r+5,WIDTH-r-5),y=Math.min(FLOOR-r,(a.position.y+b.position.y)/2);const velocity={x:clamp((a.velocity.x+b.velocity.x)/2,-3,3),y:clamp((a.velocity.y+b.velocity.y)/2,-2,2)};Matter.Composite.remove(this.engine.world,a);Matter.Composite.remove(this.engine.world,b);this.ducks=this.ducks.filter(d=>d!==a&&d!==b);const n=this.add(tier,x,y,{grace:1000,angle:(a.angle+b.angle)/2});Matter.Body.setVelocity(n,velocity);Matter.Body.setAngularVelocity(n,clamp((a.angularVelocity+b.angularVelocity)/2,-.06,.06));this.score+=TIERS[tier].points;this.highest=Math.max(this.highest,tier);this.merges++;this.onEvent({type:'merge',tier,x,y,points:TIERS[tier].points,final:tier===FINAL_TIER});}}
 finish(reason){if(this.over)return;this.over=true;this.onEvent({type:'over',reason,score:this.score})}
 snapshot(){return{score:this.score,highest:this.highest,current:this.current,next:this.next,drops:this.dropCount,merges:this.merges,paused:this.paused,over:this.over,warningMs:Math.round(this.warn),time:Math.round(this.time),ducks:this.ducks.map(b=>({tier:b.duck.tier,x:Math.round(b.position.x),y:Math.round(b.position.y),angle:+b.angle.toFixed(3)}))}}
 }
 return{Game,TIERS,FINAL_TIER,WIDTH,HEIGHT,FLOOR,LINE,SPAWN,STEP,CONTACT_EPSILON,clamp};
});
